inf112-v20/G-Unit

src/main/java/inf112/gunit/player/card/MovementCard.java
src/main/java/inf112/gunit/player/card/ProgramCard.java
src/main/java/inf112/gunit/player/card/RotationCard.java
src/test/java/inf112/gunit/cardTests/CardTests.java

*   Added simple classes for program cards. Basically just a skeleton.

Program cards -> master

---

src/main/java/inf112/gunit/board/Direction.java

Enum for direction

---

Deliverables/ObligatoriskOppgave2.md
src/main/java/inf112/gunit/player/Player.java

Feature is deprecated.
Please review @boaanes @eliasdjup @ErikAndal.

:wastebasket: Remove player movement with arrow keys

---

README.md

Added project setup doc

---

README.md

Added build setup for macOS/Linux, Windows is still WIP

:pencil: Improved the project documentation

---

pom.xml

Changed pom.xml to be able to build .jar file with all dependencies

:wrench: Updated Maven config

---

Deliverables/ObligatoriskOppgave2.md
README.md
src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java

Added support for mulitple robots on the board.
Currently the robot movement is handled by static ProgramCard arrays.

Multiple players

---

src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/player/card/TestPrograms.java
src/main/java/inf112/gunit/screens/Game.java

Implemented the doTurn-method such that it handles one program card at a time.

Proper do turn

---

src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java

1. Removed getNumberOfFlags() in class Board, since according to my "system" for registering the capturing of flags, it was no longer needed.
2. Getter and setter for flags collected in class Robot.
3. Removed the for-loop for checking if all flags have been captured because it is "repetitive".
4. Implemented a system much like "hole_mechanics", for registering if a robot has captured all the flags in the right order, and then calls gameOver(robot).
I now see that, in class Game, I should probably also remove:
private int numOfFlags;
public int getNumOfFlags() {
return numOfFlags;
}

Flag mechanics implemented

---

assets/sprites.tsx
src/main/java/inf112/gunit/board/Direction.java
src/main/java/inf112/gunit/main/Main.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java
src/test/java/inf112/gunit/player/MoveTests.java

Now fully functionales. Closing #72.

Wall mechanics

---

src/main/java/inf112/gunit/screens/Game.java
src/main/java/inf112/gunit/screens/GameOver.java

Implemented game over screen. I just copied "Menu" class and modified it. 
The winner will be displayed at the top within a String.
Below the player can choose between three options: Restart, Main Menu and Exit.

simple_game_over_screen_implemented

---

assets/sprites.tsx
src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/screens/Game.java
src/test/java/inf112/gunit/board/LaserTests.java

Implemented lasers

---

src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/player/Robot.java

Hole bug fixed.
Also backupMemory will now change to the position of the newly captured flag.

Fixed the hole bug

---

src/main/java/inf112/gunit/screens/Game.java

⚗ Added soundtrack.

---

src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java
src/main/java/inf112/gunit/screens/GameOver.java

Dead AI will now be removed from the board.
Now, if the player loses, in Game Over Screen, the message displayed will be different from when someone wins.
I also made a new boolean "dead" in robot + a getter for it.
Also made a few comments.

AI can die now

---

src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java
src/main/java/inf112/gunit/screens/Menu.java

Bug fixing

---

src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java
src/test/java/inf112/gunit/player/MoveTests.java

They also die if they try to move outside the map.

🐛 Robots now receive a damage token when bumping into walls.

---

src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java
src/main/java/inf112/gunit/screens/Menu.java

In the easy AI, the robots just do random moves.

✨ Implemented easy AI.

---

src/main/java/inf112/gunit/board/Board.java
src/main/java/inf112/gunit/board/Direction.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/RRScreen.java

Written javadoc for remaining methods

---

src/main/java/inf112/gunit/board/Direction.java
src/main/java/inf112/gunit/hud/Hud.java
src/main/java/inf112/gunit/player/Robot.java
src/main/java/inf112/gunit/screens/Game.java
src/main/java/inf112/gunit/screens/GameOver.java
src/main/java/inf112/gunit/screens/Menu.java
src/test/java/inf112/gunit/hud/HudCardTests.java
src/test/java/inf112/gunit/hud/PowerDownTests.java

Some codacy error fixes
